<?php get_header(); the_post(); $artist_id=get_the_ID(); $songs=orh_playlist_for_artist($artist_id); $links=get_post_meta($artist_id,'orh_stream_links',true); $contacts=get_post_meta($artist_id,'orh_contacts',true); $count=orh_artist_count($artist_id); ?>
<main class="artist-profile">
<div class="orh-breadcrumbs"><a href="<?php echo esc_url(home_url('/'));?>">Радио Хит</a><span>→</span><a href="<?php echo esc_url(get_post_type_archive_link('orh_artist'));?>">Артисты Радио Онлайн ХИТ</a><span>→</span><b><?php the_title();?></b></div>
<section class="artist-profile-head">
<div class="artist-profile-portrait"><?php if(has_post_thumbnail()){ the_post_thumbnail('large'); } else { ?><span><?php echo esc_html(function_exists('mb_strtoupper')?mb_strtoupper(mb_substr(get_the_title(),0,1)):'H');?></span><?php } ?></div>
<div class="artist-profile-info"><div class="eyebrow">АРТИСТ РАДИО ОНЛАЙН ХИТ</div><h1><?php the_title();?></h1><div class="artist-stats"><span><b><?php echo esc_html($count);?></b> треков</span><span><b>ХИТ</b> каталог</span><span><b>24/7</b> эфир</span></div><div class="artist-description"><?php the_excerpt(); ?><?php the_content(); ?></div>
<?php if($links):?><div class="artist-links"><b>Слушать и подписаться</b><?php foreach(preg_split('/\r\n|\r|\n/',$links) as $link){$link=trim($link);if(!$link)continue; $parts=explode('—',$link,2);$label=trim($parts[0]);$href=isset($parts[1])?trim($parts[1]):''; if($href&&filter_var($href,FILTER_VALIDATE_URL))echo '<a href="'.esc_url($href).'" target="_blank" rel="noopener">'.esc_html($label).' ↗</a>';else echo '<span>'.esc_html($label).'</span>'; }?></div><?php endif;?>
<?php if($contacts):?><div class="artist-contact"><span>Контакты</span><b><?php echo esc_html($contacts);?></b></div><?php endif;?></div></section>
<section class="artist-tracks"><div class="section-top"><div><div class="eyebrow">КАТАЛОГ АРТИСТА</div><h2>Песни в эфире</h2></div><span class="track-count"><?php echo esc_html($count);?> треков</span></div>
<div class="artist-track-list"><?php if($songs->have_posts()):$n=0;while($songs->have_posts()):$songs->the_post();$audio=orh_song_audio(get_the_ID());$plays=(int)get_post_meta(get_the_ID(),'orh_plays',true);$thumb=orh_media_url(get_the_ID(),'thumbnail');?><div class="artist-track"><strong><?php echo sprintf('%02d',++$n);?></strong><span class="track-art" <?php if($thumb)echo 'style="background-image:url(\''.esc_url($thumb).'\')"';?>><?php if(!$thumb)echo '♪';?></span><div><b><?php the_title();?></b><small><?php echo esc_html(number_format_i18n($plays));?> прослушиваний</small></div><button onclick="playSong(<?php echo esc_attr(get_the_ID());?>,'<?php echo esc_js(get_the_title());?>','<?php echo esc_js(get_the_title($artist_id));?>','<?php echo esc_url($audio);?>','<?php echo esc_url($thumb);?>')"><span class="mini-play-icon" aria-hidden="true"></span></button></div><?php endwhile;wp_reset_postdata();else:?><div class="empty">У артиста пока нет опубликованных треков.</div><?php endif;?></div></section>
</main><?php get_footer(); ?>