<?php get_header(); ?>
<main class="section song-archive">
<div class="orh-breadcrumbs"><a href="<?php echo esc_url(home_url('/'));?>">Радио Хит</a><span>→</span><b>Все песни</b></div>
<div class="eyebrow">МУЗЫКА ХИТ</div><h1>Все песни</h1><p class="archive-intro">Песни артистов Радио Онлайн ХИТ. Выберите трек, чтобы сразу начать прослушивание.</p>
<div class="chart">
<?php if(have_posts()): $n=0; while(have_posts()): the_post(); $id=get_the_ID(); $aid=(int)get_post_meta($id,'orh_artist_id',true); $an=$aid?get_the_title($aid):'Артист'; $au=orh_song_audio($id); $thumb=orh_media_url($id,'thumbnail'); $plays=(int)get_post_meta($id,'orh_plays',true); ?>
<div class="row song-row" role="button" tabindex="0" aria-label="Слушать <?php echo esc_attr(get_the_title());?> — <?php echo esc_attr($an);?>" onclick="playSong(<?php echo esc_attr($id);?>,'<?php echo esc_js(get_the_title());?>','<?php echo esc_js($an);?>','<?php echo esc_url($au);?>','<?php echo esc_url($thumb);?>')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();playSong(<?php echo esc_attr($id);?>,'<?php echo esc_js(get_the_title());?>','<?php echo esc_js($an);?>','<?php echo esc_url($au);?>','<?php echo esc_url($thumb);?>')}">
<strong class="song-number"><?php echo esc_html(sprintf('%02d',++$n));?></strong><span class="art art0" <?php if($thumb)echo 'style="background-image:url(\''.esc_url($thumb).'\')"';?>><?php if(!$thumb)echo '♪';?></span><div class="name"><b><?php the_title();?></b><small><?php echo esc_html($an);?></small></div><span class="song-plays"><?php echo esc_html(number_format_i18n($plays));?> прослуш.</span><button type="button" aria-label="Слушать <?php echo esc_attr(get_the_title());?>" onclick="event.stopPropagation();playSong(<?php echo esc_attr($id);?>,'<?php echo esc_js(get_the_title());?>','<?php echo esc_js($an);?>','<?php echo esc_url($au);?>','<?php echo esc_url($thumb);?>')">▶</button>
</div>
<?php endwhile; else: ?><div class="empty">Песни пока не опубликованы.</div><?php endif; ?>
</div></main><?php get_footer();?>